### 게시글 생성 요청 (POST)
POST http://localhost:8080/api/articles
Content-Type: application/json

{
    "title": "제목",
    "content": "내용"
}


### 모든 게시글 조회 요청 (GET)
GET http://localhost:8080/api/articles


### 1번 게시글 삭제 요청 (DELETE)
DELETE http://localhost:8080/api/articles/1